using CoroMES.Core.Entities;
using CoroMES.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace CoroMES.Web.Startup;

public static class DatabaseStartupExtensions
{
    public static async Task EnsureCoroMesDatabaseAsync(this WebApplication app, string dbProvider)
    {
        using var scope = app.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
        if (string.Equals(dbProvider, "postgres", StringComparison.OrdinalIgnoreCase))
        {
            await db.Database.MigrateAsync();
            await EnsureAuditTableAsync(db, dbProvider);
            await EnsureAlarmEventsTableAsync(db, dbProvider);
            await EnsureSystemSettingsTableAsync(db, dbProvider);
            await EnsureDisplayDefinitionsTableAsync(db, dbProvider);
        }
        else
        {
            await db.Database.EnsureCreatedAsync();
            await EnsureAuditTableAsync(db, dbProvider);
            await EnsureAlarmEventsTableAsync(db, dbProvider);
            await EnsureSystemSettingsTableAsync(db, dbProvider);
            await EnsureDisplayDefinitionsTableAsync(db, dbProvider);
        }

        await SeedDisplayDefinitionsAsync(db);
    }

    private static async Task EnsureAuditTableAsync(ApplicationDbContext db, string dbProvider)
    {
        if (string.Equals(dbProvider, "postgres", StringComparison.OrdinalIgnoreCase))
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "AuditLogs" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL,
                    "OccurredAtUtc" timestamp with time zone NOT NULL,
                    "Actor" character varying(120) NOT NULL,
                    "Action" character varying(80) NOT NULL,
                    "EntityName" character varying(120) NOT NULL,
                    "EntityId" integer NULL,
                    "Route" character varying(300) NULL,
                    "IpAddress" character varying(80) NULL,
                    "UserAgent" character varying(300) NULL,
                    "Succeeded" boolean NOT NULL,
                    "Summary" character varying(1000) NOT NULL,
                    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
                );
                """);
        }
        else
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "AuditLogs" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_AuditLogs" PRIMARY KEY AUTOINCREMENT,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    "CreatedBy" TEXT NULL,
                    "UpdatedBy" TEXT NULL,
                    "OccurredAtUtc" TEXT NOT NULL,
                    "Actor" TEXT NOT NULL,
                    "Action" TEXT NOT NULL,
                    "EntityName" TEXT NOT NULL,
                    "EntityId" INTEGER NULL,
                    "Route" TEXT NULL,
                    "IpAddress" TEXT NULL,
                    "UserAgent" TEXT NULL,
                    "Succeeded" INTEGER NOT NULL,
                    "Summary" TEXT NOT NULL
                );
                """);
        }

        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_AuditLogs_OccurredAtUtc" ON "AuditLogs" ("OccurredAtUtc");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_AuditLogs_EntityName_EntityId" ON "AuditLogs" ("EntityName", "EntityId");
            """);
    }

    private static async Task EnsureDisplayDefinitionsTableAsync(ApplicationDbContext db, string dbProvider)
    {
        if (string.Equals(dbProvider, "postgres", StringComparison.OrdinalIgnoreCase))
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "DisplayDefinitions" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Slug" character varying(120) NOT NULL,
                    "Name" character varying(160) NOT NULL,
                    "Type" character varying(40) NOT NULL,
                    "RefreshSeconds" integer NOT NULL,
                    "EquipmentId" integer NULL,
                    "IsActive" boolean NOT NULL,
                    "SettingsJson" character varying(4000) NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL,
                    CONSTRAINT "PK_DisplayDefinitions" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_DisplayDefinitions_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("Id") ON DELETE SET NULL
                );
                """);
        }
        else
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "DisplayDefinitions" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_DisplayDefinitions" PRIMARY KEY AUTOINCREMENT,
                    "Slug" TEXT NOT NULL,
                    "Name" TEXT NOT NULL,
                    "Type" TEXT NOT NULL,
                    "RefreshSeconds" INTEGER NOT NULL,
                    "EquipmentId" INTEGER NULL,
                    "IsActive" INTEGER NOT NULL,
                    "SettingsJson" TEXT NULL,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    "CreatedBy" TEXT NULL,
                    "UpdatedBy" TEXT NULL,
                    CONSTRAINT "FK_DisplayDefinitions_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("Id") ON DELETE SET NULL
                );
                """);
        }

        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_DisplayDefinitions_Slug" ON "DisplayDefinitions" ("Slug");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_DisplayDefinitions_EquipmentId" ON "DisplayDefinitions" ("EquipmentId");
            """);
    }

    private static async Task EnsureAlarmEventsTableAsync(ApplicationDbContext db, string dbProvider)
    {
        if (string.Equals(dbProvider, "postgres", StringComparison.OrdinalIgnoreCase))
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "AlarmEvents" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL,
                    "Source" character varying(80) NOT NULL,
                    "Title" character varying(160) NOT NULL,
                    "Message" character varying(1000) NOT NULL,
                    "Severity" integer NOT NULL,
                    "Status" integer NOT NULL,
                    "EquipmentId" integer NULL,
                    "TriggeredAtUtc" timestamp with time zone NOT NULL,
                    "AcknowledgedAtUtc" timestamp with time zone NULL,
                    "ResolvedAtUtc" timestamp with time zone NULL,
                    "AcknowledgedBy" character varying(120) NULL,
                    "ResolvedBy" character varying(120) NULL,
                    "AlertChannels" character varying(300) NULL,
                    "NotificationSummary" character varying(1000) NULL,
                    CONSTRAINT "PK_AlarmEvents" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_AlarmEvents_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("Id") ON DELETE SET NULL
                );
                """);
        }
        else
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "AlarmEvents" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_AlarmEvents" PRIMARY KEY AUTOINCREMENT,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    "CreatedBy" TEXT NULL,
                    "UpdatedBy" TEXT NULL,
                    "Source" TEXT NOT NULL,
                    "Title" TEXT NOT NULL,
                    "Message" TEXT NOT NULL,
                    "Severity" INTEGER NOT NULL,
                    "Status" INTEGER NOT NULL,
                    "EquipmentId" INTEGER NULL,
                    "TriggeredAtUtc" TEXT NOT NULL,
                    "AcknowledgedAtUtc" TEXT NULL,
                    "ResolvedAtUtc" TEXT NULL,
                    "AcknowledgedBy" TEXT NULL,
                    "ResolvedBy" TEXT NULL,
                    "AlertChannels" TEXT NULL,
                    "NotificationSummary" TEXT NULL,
                    CONSTRAINT "FK_AlarmEvents_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("Id") ON DELETE SET NULL
                );
                """);
        }

        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_AlarmEvents_Status" ON "AlarmEvents" ("Status");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_AlarmEvents_Severity" ON "AlarmEvents" ("Severity");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_AlarmEvents_TriggeredAtUtc" ON "AlarmEvents" ("TriggeredAtUtc");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_AlarmEvents_EquipmentId" ON "AlarmEvents" ("EquipmentId");
            """);
    }

    private static async Task EnsureSystemSettingsTableAsync(ApplicationDbContext db, string dbProvider)
    {
        if (string.Equals(dbProvider, "postgres", StringComparison.OrdinalIgnoreCase))
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "SystemSettings" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL,
                    "Key" character varying(120) NOT NULL,
                    "Category" character varying(80) NOT NULL,
                    "Value" character varying(1000) NOT NULL,
                    "Description" character varying(300) NOT NULL,
                    CONSTRAINT "PK_SystemSettings" PRIMARY KEY ("Id")
                );
                """);
        }
        else
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "SystemSettings" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_SystemSettings" PRIMARY KEY AUTOINCREMENT,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    "CreatedBy" TEXT NULL,
                    "UpdatedBy" TEXT NULL,
                    "Key" TEXT NOT NULL,
                    "Category" TEXT NOT NULL,
                    "Value" TEXT NOT NULL,
                    "Description" TEXT NOT NULL
                );
                """);
        }

        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_SystemSettings_Key" ON "SystemSettings" ("Key");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_SystemSettings_Category" ON "SystemSettings" ("Category");
            """);
    }

    private static async Task SeedDisplayDefinitionsAsync(ApplicationDbContext db)
    {
        if (await db.DisplayDefinitions.AnyAsync())
        {
            return;
        }

        db.DisplayDefinitions.AddRange(
            new DisplayDefinition { Slug = "line1-oee", Name = "Line 1 OEE", Type = "oee", RefreshSeconds = 5, IsActive = true },
            new DisplayDefinition { Slug = "quality", Name = "Quality Monitor", Type = "quality", RefreshSeconds = 10, IsActive = true },
            new DisplayDefinition { Slug = "equipment", Name = "Equipment Status", Type = "equipment", RefreshSeconds = 3, IsActive = true });

        await db.SaveChangesAsync();
    }
}
