using CoroMES.Core.Entities;
using CoroMES.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace CoroMES.Web.Startup;

public static class DatabaseStartupExtensions
{
    public static async Task EnsureCoroMesDatabaseAsync(this WebApplication app, string dbProvider)
    {
        using var scope = app.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
        if (string.Equals(dbProvider, "postgres", StringComparison.OrdinalIgnoreCase))
        {
            await db.Database.MigrateAsync();
            await EnsureAuditTableAsync(db, dbProvider);
            await EnsureAlarmEventsTableAsync(db, dbProvider);
            await EnsureSystemSettingsTableAsync(db, dbProvider);
            await EnsureDisplayDefinitionsTableAsync(db, dbProvider);
            await EnsureVisionTelemetryTablesAsync(db, dbProvider);
        }
        else
        {
            await db.Database.EnsureCreatedAsync();
            await EnsureAuditTableAsync(db, dbProvider);
            await EnsureAlarmEventsTableAsync(db, dbProvider);
            await EnsureSystemSettingsTableAsync(db, dbProvider);
            await EnsureDisplayDefinitionsTableAsync(db, dbProvider);
            await EnsureVisionTelemetryTablesAsync(db, dbProvider);
        }

        await SeedDisplayDefinitionsAsync(db);
    }

    private static async Task EnsureAuditTableAsync(ApplicationDbContext db, string dbProvider)
    {
        if (string.Equals(dbProvider, "postgres", StringComparison.OrdinalIgnoreCase))
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "AuditLogs" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL,
                    "OccurredAtUtc" timestamp with time zone NOT NULL,
                    "Actor" character varying(120) NOT NULL,
                    "Action" character varying(80) NOT NULL,
                    "EntityName" character varying(120) NOT NULL,
                    "EntityId" integer NULL,
                    "Route" character varying(300) NULL,
                    "IpAddress" character varying(80) NULL,
                    "UserAgent" character varying(300) NULL,
                    "Succeeded" boolean NOT NULL,
                    "Summary" character varying(1000) NOT NULL,
                    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
                );
                """);
        }
        else
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "AuditLogs" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_AuditLogs" PRIMARY KEY AUTOINCREMENT,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    "CreatedBy" TEXT NULL,
                    "UpdatedBy" TEXT NULL,
                    "OccurredAtUtc" TEXT NOT NULL,
                    "Actor" TEXT NOT NULL,
                    "Action" TEXT NOT NULL,
                    "EntityName" TEXT NOT NULL,
                    "EntityId" INTEGER NULL,
                    "Route" TEXT NULL,
                    "IpAddress" TEXT NULL,
                    "UserAgent" TEXT NULL,
                    "Succeeded" INTEGER NOT NULL,
                    "Summary" TEXT NOT NULL
                );
                """);
        }

        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_AuditLogs_OccurredAtUtc" ON "AuditLogs" ("OccurredAtUtc");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_AuditLogs_EntityName_EntityId" ON "AuditLogs" ("EntityName", "EntityId");
            """);
    }

    private static async Task EnsureDisplayDefinitionsTableAsync(ApplicationDbContext db, string dbProvider)
    {
        if (string.Equals(dbProvider, "postgres", StringComparison.OrdinalIgnoreCase))
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "DisplayDefinitions" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Slug" character varying(120) NOT NULL,
                    "Name" character varying(160) NOT NULL,
                    "Type" character varying(40) NOT NULL,
                    "RefreshSeconds" integer NOT NULL,
                    "EquipmentId" integer NULL,
                    "IsActive" boolean NOT NULL,
                    "SettingsJson" character varying(4000) NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL,
                    CONSTRAINT "PK_DisplayDefinitions" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_DisplayDefinitions_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("Id") ON DELETE SET NULL
                );
                """);
        }
        else
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "DisplayDefinitions" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_DisplayDefinitions" PRIMARY KEY AUTOINCREMENT,
                    "Slug" TEXT NOT NULL,
                    "Name" TEXT NOT NULL,
                    "Type" TEXT NOT NULL,
                    "RefreshSeconds" INTEGER NOT NULL,
                    "EquipmentId" INTEGER NULL,
                    "IsActive" INTEGER NOT NULL,
                    "SettingsJson" TEXT NULL,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    "CreatedBy" TEXT NULL,
                    "UpdatedBy" TEXT NULL,
                    CONSTRAINT "FK_DisplayDefinitions_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("Id") ON DELETE SET NULL
                );
                """);
        }

        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_DisplayDefinitions_Slug" ON "DisplayDefinitions" ("Slug");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_DisplayDefinitions_EquipmentId" ON "DisplayDefinitions" ("EquipmentId");
            """);
    }

    private static async Task EnsureAlarmEventsTableAsync(ApplicationDbContext db, string dbProvider)
    {
        if (string.Equals(dbProvider, "postgres", StringComparison.OrdinalIgnoreCase))
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "AlarmEvents" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL,
                    "Source" character varying(80) NOT NULL,
                    "Title" character varying(160) NOT NULL,
                    "Message" character varying(1000) NOT NULL,
                    "Severity" integer NOT NULL,
                    "Status" integer NOT NULL,
                    "EquipmentId" integer NULL,
                    "TriggeredAtUtc" timestamp with time zone NOT NULL,
                    "AcknowledgedAtUtc" timestamp with time zone NULL,
                    "ResolvedAtUtc" timestamp with time zone NULL,
                    "AcknowledgedBy" character varying(120) NULL,
                    "ResolvedBy" character varying(120) NULL,
                    "AlertChannels" character varying(300) NULL,
                    "NotificationSummary" character varying(1000) NULL,
                    CONSTRAINT "PK_AlarmEvents" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_AlarmEvents_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("Id") ON DELETE SET NULL
                );
                """);
        }
        else
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "AlarmEvents" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_AlarmEvents" PRIMARY KEY AUTOINCREMENT,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    "CreatedBy" TEXT NULL,
                    "UpdatedBy" TEXT NULL,
                    "Source" TEXT NOT NULL,
                    "Title" TEXT NOT NULL,
                    "Message" TEXT NOT NULL,
                    "Severity" INTEGER NOT NULL,
                    "Status" INTEGER NOT NULL,
                    "EquipmentId" INTEGER NULL,
                    "TriggeredAtUtc" TEXT NOT NULL,
                    "AcknowledgedAtUtc" TEXT NULL,
                    "ResolvedAtUtc" TEXT NULL,
                    "AcknowledgedBy" TEXT NULL,
                    "ResolvedBy" TEXT NULL,
                    "AlertChannels" TEXT NULL,
                    "NotificationSummary" TEXT NULL,
                    CONSTRAINT "FK_AlarmEvents_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("Id") ON DELETE SET NULL
                );
                """);
        }

        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_AlarmEvents_Status" ON "AlarmEvents" ("Status");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_AlarmEvents_Severity" ON "AlarmEvents" ("Severity");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_AlarmEvents_TriggeredAtUtc" ON "AlarmEvents" ("TriggeredAtUtc");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_AlarmEvents_EquipmentId" ON "AlarmEvents" ("EquipmentId");
            """);
    }

    private static async Task EnsureSystemSettingsTableAsync(ApplicationDbContext db, string dbProvider)
    {
        if (string.Equals(dbProvider, "postgres", StringComparison.OrdinalIgnoreCase))
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "SystemSettings" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL,
                    "UserId" character varying(120) NULL,
                    "Key" character varying(120) NOT NULL,
                    "Category" character varying(80) NOT NULL,
                    "Value" character varying(1000) NOT NULL,
                    "Description" character varying(300) NOT NULL,
                    CONSTRAINT "PK_SystemSettings" PRIMARY KEY ("Id")
                );
                """);
        }
        else
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "SystemSettings" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_SystemSettings" PRIMARY KEY AUTOINCREMENT,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    "CreatedBy" TEXT NULL,
                    "UpdatedBy" TEXT NULL,
                    "UserId" TEXT NULL,
                    "Key" TEXT NOT NULL,
                    "Category" TEXT NOT NULL,
                    "Value" TEXT NOT NULL,
                    "Description" TEXT NOT NULL
                );
                """);
        }

        await EnsureSystemSettingsUserIdColumnAsync(db, dbProvider);

        await db.Database.ExecuteSqlRawAsync("""
            DROP INDEX IF EXISTS "IX_SystemSettings_Key";
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_SystemSettings_UserId_Key" ON "SystemSettings" ("UserId", "Key");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_SystemSettings_Category" ON "SystemSettings" ("Category");
            """);
    }

    private static async Task EnsureSystemSettingsUserIdColumnAsync(ApplicationDbContext db, string dbProvider)
    {
        if (string.Equals(dbProvider, "postgres", StringComparison.OrdinalIgnoreCase))
        {
            await db.Database.ExecuteSqlRawAsync("""
                ALTER TABLE "SystemSettings" ADD COLUMN IF NOT EXISTS "UserId" character varying(120) NULL;
                """);

            return;
        }

        var columns = await db.Database
            .SqlQueryRaw<string>("SELECT name AS Value FROM pragma_table_info('SystemSettings');")
            .ToListAsync();

        if (!columns.Contains("UserId", StringComparer.OrdinalIgnoreCase))
        {
            await db.Database.ExecuteSqlRawAsync("""
                ALTER TABLE "SystemSettings" ADD COLUMN "UserId" TEXT NULL;
                """);
        }
    }

    private static async Task EnsureVisionTelemetryTablesAsync(ApplicationDbContext db, string dbProvider)
    {
        if (string.Equals(dbProvider, "postgres", StringComparison.OrdinalIgnoreCase))
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "VisionSources" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL,
                    "ExternalSystemId" character varying(120) NOT NULL,
                    "DisplayName" character varying(160) NOT NULL,
                    "EndpointBaseUrl" character varying(500) NOT NULL,
                    "DashboardBaseUrl" character varying(500) NULL,
                    "EquipmentId" integer NULL,
                    "IsActive" boolean NOT NULL,
                    "LastSeenAtUtc" timestamp with time zone NULL,
                    "LastCollectedAtUtc" timestamp with time zone NULL,
                    "LastError" character varying(1000) NULL,
                    CONSTRAINT "PK_VisionSources" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_VisionSources_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("Id") ON DELETE SET NULL
                );
                """);

            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "VisionCameras" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL,
                    "VisionSourceId" integer NOT NULL,
                    "ElementId" character varying(160) NOT NULL,
                    "DisplayName" character varying(160) NOT NULL,
                    "SlotId" character varying(80) NULL,
                    "Source" character varying(200) NULL,
                    "SourceType" character varying(80) NULL,
                    "EquipmentId" integer NULL,
                    "IsActive" boolean NOT NULL,
                    "LastSeenAtUtc" timestamp with time zone NULL,
                    "LastStatus" character varying(80) NULL,
                    "LastMotionLevel" double precision NULL,
                    CONSTRAINT "PK_VisionCameras" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_VisionCameras_VisionSources_VisionSourceId" FOREIGN KEY ("VisionSourceId") REFERENCES "VisionSources" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_VisionCameras_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("Id") ON DELETE SET NULL
                );
                """);

            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "VisionZones" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL,
                    "VisionSourceId" integer NOT NULL,
                    "VisionCameraId" integer NULL,
                    "ElementId" character varying(160) NOT NULL,
                    "Name" character varying(160) NOT NULL,
                    "EquipmentId" integer NULL,
                    "Enabled" boolean NOT NULL,
                    "LastStatus" character varying(80) NULL,
                    "LastMotionPercent" double precision NULL,
                    "LastSeenAtUtc" timestamp with time zone NULL,
                    CONSTRAINT "PK_VisionZones" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_VisionZones_VisionSources_VisionSourceId" FOREIGN KEY ("VisionSourceId") REFERENCES "VisionSources" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_VisionZones_VisionCameras_VisionCameraId" FOREIGN KEY ("VisionCameraId") REFERENCES "VisionCameras" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_VisionZones_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("Id") ON DELETE SET NULL
                );
                """);

            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "VisionReadings" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL,
                    "VisionSourceId" integer NOT NULL,
                    "VisionCameraId" integer NULL,
                    "VisionZoneId" integer NULL,
                    "ElementId" character varying(160) NOT NULL,
                    "OccurredAtUtc" timestamp with time zone NOT NULL,
                    "CollectedAtUtc" timestamp with time zone NOT NULL,
                    "Metric" character varying(120) NOT NULL,
                    "NumericValue" double precision NULL,
                    "TextValue" character varying(500) NULL,
                    "BooleanValue" boolean NULL,
                    "Quality" character varying(80) NULL,
                    "RawJson" character varying(4000) NOT NULL,
                    CONSTRAINT "PK_VisionReadings" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_VisionReadings_VisionSources_VisionSourceId" FOREIGN KEY ("VisionSourceId") REFERENCES "VisionSources" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_VisionReadings_VisionCameras_VisionCameraId" FOREIGN KEY ("VisionCameraId") REFERENCES "VisionCameras" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_VisionReadings_VisionZones_VisionZoneId" FOREIGN KEY ("VisionZoneId") REFERENCES "VisionZones" ("Id") ON DELETE SET NULL
                );
                """);

            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "VisionEvents" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL,
                    "VisionSourceId" integer NOT NULL,
                    "VisionCameraId" integer NULL,
                    "VisionZoneId" integer NULL,
                    "OccurredAtUtc" timestamp with time zone NOT NULL,
                    "CollectedAtUtc" timestamp with time zone NOT NULL,
                    "Source" character varying(200) NULL,
                    "Status" character varying(80) NOT NULL,
                    "MotionPercent" double precision NULL,
                    "Region" character varying(160) NULL,
                    "RawJson" character varying(4000) NOT NULL,
                    CONSTRAINT "PK_VisionEvents" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_VisionEvents_VisionSources_VisionSourceId" FOREIGN KEY ("VisionSourceId") REFERENCES "VisionSources" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_VisionEvents_VisionCameras_VisionCameraId" FOREIGN KEY ("VisionCameraId") REFERENCES "VisionCameras" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_VisionEvents_VisionZones_VisionZoneId" FOREIGN KEY ("VisionZoneId") REFERENCES "VisionZones" ("Id") ON DELETE SET NULL
                );
                """);
        }
        else
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "VisionSources" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_VisionSources" PRIMARY KEY AUTOINCREMENT,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    "CreatedBy" TEXT NULL,
                    "UpdatedBy" TEXT NULL,
                    "ExternalSystemId" TEXT NOT NULL,
                    "DisplayName" TEXT NOT NULL,
                    "EndpointBaseUrl" TEXT NOT NULL,
                    "DashboardBaseUrl" TEXT NULL,
                    "EquipmentId" INTEGER NULL,
                    "IsActive" INTEGER NOT NULL,
                    "LastSeenAtUtc" TEXT NULL,
                    "LastCollectedAtUtc" TEXT NULL,
                    "LastError" TEXT NULL,
                    CONSTRAINT "FK_VisionSources_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("Id") ON DELETE SET NULL
                );
                """);

            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "VisionCameras" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_VisionCameras" PRIMARY KEY AUTOINCREMENT,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    "CreatedBy" TEXT NULL,
                    "UpdatedBy" TEXT NULL,
                    "VisionSourceId" INTEGER NOT NULL,
                    "ElementId" TEXT NOT NULL,
                    "DisplayName" TEXT NOT NULL,
                    "SlotId" TEXT NULL,
                    "Source" TEXT NULL,
                    "SourceType" TEXT NULL,
                    "EquipmentId" INTEGER NULL,
                    "IsActive" INTEGER NOT NULL,
                    "LastSeenAtUtc" TEXT NULL,
                    "LastStatus" TEXT NULL,
                    "LastMotionLevel" REAL NULL,
                    CONSTRAINT "FK_VisionCameras_VisionSources_VisionSourceId" FOREIGN KEY ("VisionSourceId") REFERENCES "VisionSources" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_VisionCameras_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("Id") ON DELETE SET NULL
                );
                """);

            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "VisionZones" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_VisionZones" PRIMARY KEY AUTOINCREMENT,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    "CreatedBy" TEXT NULL,
                    "UpdatedBy" TEXT NULL,
                    "VisionSourceId" INTEGER NOT NULL,
                    "VisionCameraId" INTEGER NULL,
                    "ElementId" TEXT NOT NULL,
                    "Name" TEXT NOT NULL,
                    "EquipmentId" INTEGER NULL,
                    "Enabled" INTEGER NOT NULL,
                    "LastStatus" TEXT NULL,
                    "LastMotionPercent" REAL NULL,
                    "LastSeenAtUtc" TEXT NULL,
                    CONSTRAINT "FK_VisionZones_VisionSources_VisionSourceId" FOREIGN KEY ("VisionSourceId") REFERENCES "VisionSources" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_VisionZones_VisionCameras_VisionCameraId" FOREIGN KEY ("VisionCameraId") REFERENCES "VisionCameras" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_VisionZones_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("Id") ON DELETE SET NULL
                );
                """);

            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "VisionReadings" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_VisionReadings" PRIMARY KEY AUTOINCREMENT,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    "CreatedBy" TEXT NULL,
                    "UpdatedBy" TEXT NULL,
                    "VisionSourceId" INTEGER NOT NULL,
                    "VisionCameraId" INTEGER NULL,
                    "VisionZoneId" INTEGER NULL,
                    "ElementId" TEXT NOT NULL,
                    "OccurredAtUtc" TEXT NOT NULL,
                    "CollectedAtUtc" TEXT NOT NULL,
                    "Metric" TEXT NOT NULL,
                    "NumericValue" REAL NULL,
                    "TextValue" TEXT NULL,
                    "BooleanValue" INTEGER NULL,
                    "Quality" TEXT NULL,
                    "RawJson" TEXT NOT NULL,
                    CONSTRAINT "FK_VisionReadings_VisionSources_VisionSourceId" FOREIGN KEY ("VisionSourceId") REFERENCES "VisionSources" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_VisionReadings_VisionCameras_VisionCameraId" FOREIGN KEY ("VisionCameraId") REFERENCES "VisionCameras" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_VisionReadings_VisionZones_VisionZoneId" FOREIGN KEY ("VisionZoneId") REFERENCES "VisionZones" ("Id") ON DELETE SET NULL
                );
                """);

            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "VisionEvents" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_VisionEvents" PRIMARY KEY AUTOINCREMENT,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    "CreatedBy" TEXT NULL,
                    "UpdatedBy" TEXT NULL,
                    "VisionSourceId" INTEGER NOT NULL,
                    "VisionCameraId" INTEGER NULL,
                    "VisionZoneId" INTEGER NULL,
                    "OccurredAtUtc" TEXT NOT NULL,
                    "CollectedAtUtc" TEXT NOT NULL,
                    "Source" TEXT NULL,
                    "Status" TEXT NOT NULL,
                    "MotionPercent" REAL NULL,
                    "Region" TEXT NULL,
                    "RawJson" TEXT NOT NULL,
                    CONSTRAINT "FK_VisionEvents_VisionSources_VisionSourceId" FOREIGN KEY ("VisionSourceId") REFERENCES "VisionSources" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_VisionEvents_VisionCameras_VisionCameraId" FOREIGN KEY ("VisionCameraId") REFERENCES "VisionCameras" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_VisionEvents_VisionZones_VisionZoneId" FOREIGN KEY ("VisionZoneId") REFERENCES "VisionZones" ("Id") ON DELETE SET NULL
                );
                """);
        }

        await EnsureVisionZoneEquipmentColumnAsync(db, dbProvider);

        await db.Database.ExecuteSqlRawAsync("""CREATE UNIQUE INDEX IF NOT EXISTS "IX_VisionSources_ExternalSystemId" ON "VisionSources" ("ExternalSystemId");""");
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_VisionSources_IsActive" ON "VisionSources" ("IsActive");""");
        await db.Database.ExecuteSqlRawAsync("""CREATE UNIQUE INDEX IF NOT EXISTS "IX_VisionCameras_VisionSourceId_ElementId" ON "VisionCameras" ("VisionSourceId", "ElementId");""");
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_VisionCameras_EquipmentId" ON "VisionCameras" ("EquipmentId");""");
        await db.Database.ExecuteSqlRawAsync("""CREATE UNIQUE INDEX IF NOT EXISTS "IX_VisionZones_VisionSourceId_ElementId" ON "VisionZones" ("VisionSourceId", "ElementId");""");
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_VisionZones_VisionCameraId" ON "VisionZones" ("VisionCameraId");""");
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_VisionZones_EquipmentId" ON "VisionZones" ("EquipmentId");""");
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_VisionReadings_OccurredAtUtc" ON "VisionReadings" ("OccurredAtUtc");""");
        await db.Database.ExecuteSqlRawAsync("""CREATE UNIQUE INDEX IF NOT EXISTS "IX_VisionReadings_VisionSourceId_ElementId_Metric_OccurredAtUtc" ON "VisionReadings" ("VisionSourceId", "ElementId", "Metric", "OccurredAtUtc");""");
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_VisionReadings_VisionCameraId" ON "VisionReadings" ("VisionCameraId");""");
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_VisionReadings_VisionZoneId" ON "VisionReadings" ("VisionZoneId");""");
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_VisionEvents_OccurredAtUtc" ON "VisionEvents" ("OccurredAtUtc");""");
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_VisionEvents_VisionSourceId_OccurredAtUtc_Status" ON "VisionEvents" ("VisionSourceId", "OccurredAtUtc", "Status");""");
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_VisionEvents_VisionCameraId" ON "VisionEvents" ("VisionCameraId");""");
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_VisionEvents_VisionZoneId" ON "VisionEvents" ("VisionZoneId");""");
    }

    private static async Task EnsureVisionZoneEquipmentColumnAsync(ApplicationDbContext db, string dbProvider)
    {
        if (string.Equals(dbProvider, "postgres", StringComparison.OrdinalIgnoreCase))
        {
            await db.Database.ExecuteSqlRawAsync("""
                ALTER TABLE "VisionZones" ADD COLUMN IF NOT EXISTS "EquipmentId" integer NULL;
                """);

            return;
        }

        var columns = await db.Database
            .SqlQueryRaw<string>("SELECT name AS Value FROM pragma_table_info('VisionZones');")
            .ToListAsync();

        if (!columns.Contains("EquipmentId", StringComparer.OrdinalIgnoreCase))
        {
            await db.Database.ExecuteSqlRawAsync("""
                ALTER TABLE "VisionZones" ADD COLUMN "EquipmentId" INTEGER NULL;
                """);
        }
    }

    private static async Task SeedDisplayDefinitionsAsync(ApplicationDbContext db)
    {
        if (await db.DisplayDefinitions.AnyAsync())
        {
            return;
        }

        db.DisplayDefinitions.AddRange(
            new DisplayDefinition { Slug = "line1-oee", Name = "Line 1 OEE", Type = "oee", RefreshSeconds = 5, IsActive = true },
            new DisplayDefinition { Slug = "quality", Name = "Quality Monitor", Type = "quality", RefreshSeconds = 10, IsActive = true },
            new DisplayDefinition { Slug = "equipment", Name = "Equipment Status", Type = "equipment", RefreshSeconds = 3, IsActive = true });

        await db.SaveChangesAsync();
    }
}
